//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AdsCaptcha.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AdsCaptcha_DevEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AdsCaptcha_DevEntities1 object using the connection string found in the 'AdsCaptcha_DevEntities1' section of the application configuration file.
        /// </summary>
        public AdsCaptcha_DevEntities1() : base("name=AdsCaptcha_DevEntities1", "AdsCaptcha_DevEntities1")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdsCaptcha_DevEntities1 object.
        /// </summary>
        public AdsCaptcha_DevEntities1(string connectionString) : base(connectionString, "AdsCaptcha_DevEntities1")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AdsCaptcha_DevEntities1 object.
        /// </summary>
        public AdsCaptcha_DevEntities1(EntityConnection connection) : base(connection, "AdsCaptcha_DevEntities1")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_PRESS> T_PRESS
        {
            get
            {
                if ((_T_PRESS == null))
                {
                    _T_PRESS = base.CreateObjectSet<T_PRESS>("T_PRESS");
                }
                return _T_PRESS;
            }
        }
        private ObjectSet<T_PRESS> _T_PRESS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_PRESS_INQUIRES> T_PRESS_INQUIRES
        {
            get
            {
                if ((_T_PRESS_INQUIRES == null))
                {
                    _T_PRESS_INQUIRES = base.CreateObjectSet<T_PRESS_INQUIRES>("T_PRESS_INQUIRES");
                }
                return _T_PRESS_INQUIRES;
            }
        }
        private ObjectSet<T_PRESS_INQUIRES> _T_PRESS_INQUIRES;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_PRESS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_PRESS(T_PRESS t_PRESS)
        {
            base.AddObject("T_PRESS", t_PRESS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_PRESS_INQUIRES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_PRESS_INQUIRES(T_PRESS_INQUIRES t_PRESS_INQUIRES)
        {
            base.AddObject("T_PRESS_INQUIRES", t_PRESS_INQUIRES);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdsCaptcha_DevModel", Name="T_PRESS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_PRESS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_PRESS object.
        /// </summary>
        /// <param name="pressID">Initial value of the PressID property.</param>
        /// <param name="header">Initial value of the Header property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="insertDate">Initial value of the InsertDate property.</param>
        /// <param name="lastUpdateDate">Initial value of the LastUpdateDate property.</param>
        /// <param name="isDeleted">Initial value of the IsDeleted property.</param>
        /// <param name="summary">Initial value of the Summary property.</param>
        public static T_PRESS CreateT_PRESS(global::System.Int32 pressID, global::System.String header, global::System.String body, global::System.DateTime insertDate, global::System.DateTime lastUpdateDate, global::System.Boolean isDeleted, global::System.String summary)
        {
            T_PRESS t_PRESS = new T_PRESS();
            t_PRESS.PressID = pressID;
            t_PRESS.Header = header;
            t_PRESS.Body = body;
            t_PRESS.InsertDate = insertDate;
            t_PRESS.LastUpdateDate = lastUpdateDate;
            t_PRESS.IsDeleted = isDeleted;
            t_PRESS.Summary = summary;
            return t_PRESS;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PressID
        {
            get
            {
                return _PressID;
            }
            set
            {
                if (_PressID != value)
                {
                    OnPressIDChanging(value);
                    ReportPropertyChanging("PressID");
                    _PressID = StructuralObject.SetValidValue(value, "PressID");
                    ReportPropertyChanged("PressID");
                    OnPressIDChanged();
                }
            }
        }
        private global::System.Int32 _PressID;
        partial void OnPressIDChanging(global::System.Int32 value);
        partial void OnPressIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Header
        {
            get
            {
                return _Header;
            }
            set
            {
                OnHeaderChanging(value);
                ReportPropertyChanging("Header");
                _Header = StructuralObject.SetValidValue(value, false, "Header");
                ReportPropertyChanged("Header");
                OnHeaderChanged();
            }
        }
        private global::System.String _Header;
        partial void OnHeaderChanging(global::System.String value);
        partial void OnHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false, "Body");
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PressSource
        {
            get
            {
                return _PressSource;
            }
            set
            {
                OnPressSourceChanging(value);
                ReportPropertyChanging("PressSource");
                _PressSource = StructuralObject.SetValidValue(value, true, "PressSource");
                ReportPropertyChanged("PressSource");
                OnPressSourceChanged();
            }
        }
        private global::System.String _PressSource;
        partial void OnPressSourceChanging(global::System.String value);
        partial void OnPressSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PressSourceUrl
        {
            get
            {
                return _PressSourceUrl;
            }
            set
            {
                OnPressSourceUrlChanging(value);
                ReportPropertyChanging("PressSourceUrl");
                _PressSourceUrl = StructuralObject.SetValidValue(value, true, "PressSourceUrl");
                ReportPropertyChanged("PressSourceUrl");
                OnPressSourceUrlChanged();
            }
        }
        private global::System.String _PressSourceUrl;
        partial void OnPressSourceUrlChanging(global::System.String value);
        partial void OnPressSourceUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentUrl
        {
            get
            {
                return _AttachmentUrl;
            }
            set
            {
                OnAttachmentUrlChanging(value);
                ReportPropertyChanging("AttachmentUrl");
                _AttachmentUrl = StructuralObject.SetValidValue(value, true, "AttachmentUrl");
                ReportPropertyChanged("AttachmentUrl");
                OnAttachmentUrlChanged();
            }
        }
        private global::System.String _AttachmentUrl;
        partial void OnAttachmentUrlChanging(global::System.String value);
        partial void OnAttachmentUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime InsertDate
        {
            get
            {
                return _InsertDate;
            }
            set
            {
                OnInsertDateChanging(value);
                ReportPropertyChanging("InsertDate");
                _InsertDate = StructuralObject.SetValidValue(value, "InsertDate");
                ReportPropertyChanged("InsertDate");
                OnInsertDateChanged();
            }
        }
        private global::System.DateTime _InsertDate;
        partial void OnInsertDateChanging(global::System.DateTime value);
        partial void OnInsertDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdateDate
        {
            get
            {
                return _LastUpdateDate;
            }
            set
            {
                OnLastUpdateDateChanging(value);
                ReportPropertyChanging("LastUpdateDate");
                _LastUpdateDate = StructuralObject.SetValidValue(value, "LastUpdateDate");
                ReportPropertyChanged("LastUpdateDate");
                OnLastUpdateDateChanged();
            }
        }
        private global::System.DateTime _LastUpdateDate;
        partial void OnLastUpdateDateChanging(global::System.DateTime value);
        partial void OnLastUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value, "IsDeleted");
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.Boolean _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Boolean value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] PDF
        {
            get
            {
                return StructuralObject.GetValidValue(_PDF);
            }
            set
            {
                OnPDFChanging(value);
                ReportPropertyChanging("PDF");
                _PDF = StructuralObject.SetValidValue(value, true, "PDF");
                ReportPropertyChanged("PDF");
                OnPDFChanged();
            }
        }
        private global::System.Byte[] _PDF;
        partial void OnPDFChanging(global::System.Byte[] value);
        partial void OnPDFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, false, "Summary");
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AdsCaptcha_DevModel", Name="T_PRESS_INQUIRES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_PRESS_INQUIRES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_PRESS_INQUIRES object.
        /// </summary>
        /// <param name="inquireID">Initial value of the InquireID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="insertDate">Initial value of the InsertDate property.</param>
        public static T_PRESS_INQUIRES CreateT_PRESS_INQUIRES(global::System.Int32 inquireID, global::System.String firstName, global::System.String lastName, global::System.String email, global::System.DateTime insertDate)
        {
            T_PRESS_INQUIRES t_PRESS_INQUIRES = new T_PRESS_INQUIRES();
            t_PRESS_INQUIRES.InquireID = inquireID;
            t_PRESS_INQUIRES.FirstName = firstName;
            t_PRESS_INQUIRES.LastName = lastName;
            t_PRESS_INQUIRES.Email = email;
            t_PRESS_INQUIRES.InsertDate = insertDate;
            return t_PRESS_INQUIRES;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InquireID
        {
            get
            {
                return _InquireID;
            }
            set
            {
                if (_InquireID != value)
                {
                    OnInquireIDChanging(value);
                    ReportPropertyChanging("InquireID");
                    _InquireID = StructuralObject.SetValidValue(value, "InquireID");
                    ReportPropertyChanged("InquireID");
                    OnInquireIDChanged();
                }
            }
        }
        private global::System.Int32 _InquireID;
        partial void OnInquireIDChanging(global::System.Int32 value);
        partial void OnInquireIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true, "Company");
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true, "Message");
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime InsertDate
        {
            get
            {
                return _InsertDate;
            }
            set
            {
                OnInsertDateChanging(value);
                ReportPropertyChanging("InsertDate");
                _InsertDate = StructuralObject.SetValidValue(value, "InsertDate");
                ReportPropertyChanged("InsertDate");
                OnInsertDateChanged();
            }
        }
        private global::System.DateTime _InsertDate;
        partial void OnInsertDateChanging(global::System.DateTime value);
        partial void OnInsertDateChanged();

        #endregion

    }

    #endregion

}
