<%@ Page EnableViewStateMac="false" Title="Sliding Captcha - Site Owners | Inqwise" Language="C#" MasterPageFile="~/AdsCaptcha.Master" AutoEventWireup="true" CodeFile="CaptchaSiteOwners.aspx.cs" Inherits="Inqwise.AdsCaptcha.Publisher.CaptchaSiteOwners" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">

</asp:Content>

<asp:Content ID="Content5" ContentPlaceHolderID="BodyContent" runat="server">
id="body" class="page"
</asp:Content> 

<asp:Content ID="LoginContent" ContentPlaceHolderID="LoginContent" runat="server">
	<div>
		<ul class="menu-top">
			<li><a href="/aboutus.aspx" title="About Us">About Us</a></li>
			<li><a href="/products.aspx" title="Products">Products</a></li>
			<!-- <li><a id="loginBox" href="#login-box" class="login-window">SIGN IN</a></li> -->
			<li><a id="signBox" href="SignUp.aspx">SIGN UP</a></li>
		</ul>
	</div>
	<div class="menu-lobby-container">	
		<ul class="menu-lobby">
			<li><a href="/advertiser/StartPage.aspx" title="Advertisers" class="button-green"><span>Advertisers</span></a></li>
			<li><a href="StartPage.aspx" title="Site Owners" class="button-green"><span>Site Owners</span></a></li>
		</ul>
	</div> 
</asp:Content>

<asp:content ContentPlaceHolderID="MainContent" runat="server">


	<div class="content">
		<div class="middle-content">
			<div class="inner-middle-content">
				<div class="middle-status"><h2>Sliding Captcha - Site Owners</h2></div>
			</div>
		</div>
		<div class="inner-wrapper">
			<div class="inner-content">
			
				<div class="inner">
					<div class="inner-left">
						
<h1 class="oswald"><span class="green font-size-48">Secure your site. Improve user experience.</span><br/> <span class="font-size-60 top-minus-18">Generate new revenue</span></h1><br/>
						
<p>Inqwise's Sliding Captcha&trade; empowers you to:</p><br/>
<ul class="list-square margin-bottom-14" style="margin-left: 20px;">
	<li>Enhance your site's security and protection from hackers</li>
	<li>Improve user experience by replacing standard captchas that so many find annoying and difficult to read</li>
	<li>Increase conversion - 94% on average, 24% higher than the industry average</li>
	<li>Generate new revenue by monetizing our Sliding Captcha&trade; with engaging, lean-in brand advertising</li>
	<li>Offer your advertisers a high performance advertising platform: 1-3% CTR, 10-30x average CTR generated by banners</li>
</ul>
<br/>
<p>Learn how easy it is to integrate Inqwise's Sliding Captcha&trade; platform and how you can monetize each and every captcha!</p><br/>  
<p>We'd love to hear from you - <a title="Contact us" href="/contactus.aspx">contact us</a> anytime to learn more about Sliding Captcha!</p>
<br/>
<br/>
<h3 class="font-size-36"><span>Try it out</span> now</h3>
<div style="padding-top: 24px;">
	<script type="text/javascript" src="<%=ApiUrl%>slider/get.ashx?imageTypeId=5&w=300&h=250"></script>
</div>
						
						<!--
						<h2 class="">Unmatchable site security and getting paid per slide,<br/> all managed by a easy to use admin panel.</h2>
						<p class="padding-top-16">Captcha with higher security, the most user enjoyment! Get paid to block hackers from your site!</p>
						<h3 class="green padding-top-24">SLIDING CAPTCHA</h3>
						<p class="padding-top-16">Discover what it means to win with the innovative Sliding captchas.<br/> Deliver an enjoyable user experience that is proven to be engaging, higher (94%) success rates,<br/> and a powerful source of income for you.</p>
						<h3 class="green padding-top-24">EASY INTEGRATION</h3>
						<p class="padding-top-16">The Inqwise web-based platform is simple and user-friendly. We've done the hard part, all you need to do is define your settings, integrate a simple script or install plug-in. Sliding captcha works on any modern web browser including mobile and tablet devices.</p>
						<h3 class="green padding-top-24">MAKE MONEY &amp; REDUCE BOUNCE RATE</h3>
						<p class="padding-top-16">Monetize your CAPTCHAs and increase the success rate while reduce bounce rate on your web site without compromising on security. Sliding captchas give you the one of the best security available on the web today</p>
						<h3 class="green padding-top-24">THREE MODES OF CAPTCHA</h3>
						<p class="padding-top-16">You can select between three ways of operating your CAPTCHA</p>
						<ul class="list-square-green margin-bottom-14 padding-top-16">
							<li>Non Commercial - Security Only service. A random picture will be Displayed in your CAPTCHA image. No income generated for the Site Owner nor ads are displayed in this mode. The service is Free, (up to 15,000 CAPTCHAS per month). Email if you need more</li>
							<li>Commercial - Income generating CAPTCHA. An ad will be displayed as the CAPTCHA image, your revenue will be generated as your users will Fit /Click the ad in your CAPTCHA (No revenue is Guaranteed)</li>
							<li>House Ads - Use your CAPTCHA to promote your Brand / Products / Services. Your CAPTCHA images will be displayed only on your site. The service is Free (up to 15,000 CAPTCHAs) per month. <a href="/contactus.aspx" title="Contact Us">Email if you need more</a></li>
						</ul>
						
						
						<div class="padding-top-24"><img src="/images/accountpage.png" width="640" alt="" /></div>
							
						-->
							
						<br/>
						<br/>
						<br/>
						<div style="text-align: center;">
							<a href="SignUp.aspx" title="Sign Up" class="button-black"><span class="sign-up">Sign Up</span></a>
						</div>
					</div>
					<div class="inner-right">
						<div style="margin-left: 34px">
							<div>
								<a href="/products.aspx" title="Products"><img src="/images/Inqwise_animated.gif" alt="" /></a>
							</div>
							<div class="padding-top-24">
								<h3>Slide unit</h3>
								<ul class="list-square-green margin-bottom-14 padding-top-16">
									<li>94% conversion (vs. 76% industry<br/> standard)</li>
									<li>Enhanced site security</li>
									<li>Free Security monitor</li>
									<li>New revenue stream</li>
								</ul>
							</div>
							<div class="padding-top-24">
								<h3>INTEGRATING</h3>
								<p class="padding-top-16">Installing Sliding captcha is as simple as adding a few lines of code to your website.<br/> Inqwise supports a range of programming languages, including C# ASP.NET, <br/>VB ASP.NET, PHP, Java, ASP, Python, Perl, Joomla Plugin, WordPress Plugin, Drupal Plugin, DotNetNuke, vBulletin, and phpBB Plugin.</p>
							</div>
							<div class="padding-top-24">
								<h3>PROFITING</h3>
								<p class="padding-top-16">Be in complete control and monetize your site content to maximize your profits. We optimize your eCPM with the ideal advertising combination for your site, and you watch the profits roll in with our management system.</p>
							</div>
						</div>
					</div>
				</div>
			
				
			</div>
		</div>
	</div>


</asp:content>





