<%@ Page EnableViewStateMac="false" Title="Site Owners | Inqwise" Language="C#" MasterPageFile="~/AdsCaptcha.Master" AutoEventWireup="true" CodeFile="SlidingCaptcha.aspx.cs" Inherits="Inqwise.AdsCaptcha.Publisher.SlidingCaptcha" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server"> 

</asp:Content>

<asp:Content ID="Content5" ContentPlaceHolderID="BodyContent" runat="server">
id="body" class="page"
</asp:Content> 

<asp:Content ID="Content2" ContentPlaceHolderID="LoginContent" runat="server">
	
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="LoginScriptContent" runat="server"> 

</asp:Content>
<asp:content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">

   <div class="content">
		
		<div class="breadcrumbs">
			<a href="/" title="Home">Home</a>&nbsp;&rsaquo;&nbsp;Sliding Captcha&trade;&nbsp;&rsaquo;&nbsp;Site Owners
		</div>
		<div class="inner-wrapper">
			<div class="inner-content">
				<div class="page-heading-wrapper">
					<h1>Sliding Captcha&trade;</h1>
				</div>
				<div class="inner-content-left-side">
					<div>
						<script type="text/javascript" src="<%=ApiUrl%>slider/get.ashx?imageTypeId=5&w=300&h=250"></script>
					</div>
					<br/>
					<div class="color-green">Try it now</div>
					<br/>
					<br/>
					<br/>
					<br/>
					<div>
						<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
						<!-- In CAPTCHA  125X125 -->
						<ins class="adsbygoogle"
						     style="display:inline-block;width:125px;height:125px"
						     data-ad-client="ca-pub-2884927756728455"
						     data-ad-slot="8860590529"></ins>
						<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
						</script>
					</div>
					<br/>
					<br/>
					<div>
						<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
						<!-- In CAPTCHA 234X60 -->
						<ins class="adsbygoogle"
						     style="display:inline-block;width:234px;height:60px"
						     data-ad-client="ca-pub-2884927756728455"
						     data-ad-slot="8581388925"></ins>
						<script>
						(adsbygoogle = window.adsbygoogle || []).push({});
						</script>
					</div>
				</div>
				<div class="inner-content-right-side">
					<h4>Site Owners</h4>
					<div class="desc">
					<h3>Secure your site. Improve user experience.</h3><br/>
					<p>Captchas serve as vital tools to secure your site and protect it from hackers. Too often, however, they are difficult to read and can harm your site's user expirience, deterring visitors and posing an obstacle to conversion. Until now!</p><br/>
					<p>Inqwise's Sliding Captcha&trade; empowers you to:</p><br/>
					<ul style="margin: 0 20px;text-align: justify;" class="list-square-green margin-bottom-14">
						<li>Enhance your site's security and protection from hackers</li>
						<li>Improve user experience by replacing standard captchas that so many find annoying and difficult to read</li>
						<li>Increase conversion - 94% on average, 24% higher than the industry average</li>
						<li>Generate new revenue by monetizing our Sliding Captcha&trade; with engaging, lean-in brand advertising</li>
						<li>Offer your advertisers a high performance advertising platform: 1-3% CTR, 10-30x average CTR generated by banners</li>
					</ul>
					<br/>
					<p><a href="/resources.aspx">Learn how easy</a> it is to integrate Inqwise's Sliding Captcha&trade; platform and how you can monetize each and every captcha!</p><br/>  
					<p>We'd love to hear from you - <a title="Contact us" href="/contactus.aspx">contact us</a> anytime to learn more about Sliding Captcha&trade;!</p>
					</div>
					<a href="/publisher/signup.aspx" title="Get Captcha" class="button-green"><span>Get Captcha</span></a>
					<br/>
					<br/>
					<div class="text-align-right">
					Sliding Captcha&trade; <a href="/advertiser/slidingcaptcha.aspx" title="Sliding Captcha&trade; for advertisers">for advertisers &gt;&gt;</a>
					</div>
					<br/>
					<br/>
				</div>
    		</div>
    	</div>
    </div>
    
</asp:content>