<%@ Page EnableViewStateMac="false" Language="C#" MasterPageFile="AdsCaptcha.Master" AutoEventWireup="true" CodeFile="TermsOfUse.aspx.cs" Inherits="Inqwise.AdsCaptcha.TermsOfUse" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">

</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="BodyContent" runat="server">
id="supportpage" class="page"
</asp:Content>
<asp:Content ID="LoginContent" ContentPlaceHolderID="LoginContent" runat="server">
	
</asp:Content>
<asp:content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

	<div class="content">
		<div class="breadcrumbs">
			<a href="/" title="Home">Home</a>&nbsp;&rsaquo;&nbsp;Terms of Service
		</div>
		<div class="inner-wrapper">
			<div class="inner-content">
				<div class="page-heading-wrapper">
					<h1>Terms of Service</h1>
				</div>
				<div>
	            Welcome to the website of Inqwise Ltd. ("<b>Inqwise</b>"). By accessing Inqwise's website (the "<b>Site</b>") or using the services offered by Inqwise therein and as set forth in Section 3 below (the "<b>Services</b>") you agree and acknowledge to be bound by these terms of Services (the "<b>Terms</b>"). You may not use the Services if you do not accept the Terms. If you do not accept and agree to these Terms, please do not access the Site or use the Services. You may not use the Services and may not accept the Terms if you are a person barred from receiving the Services under applicable laws including the laws of the country in which you are resident or from which you use the Services.<br />
	            Inqwise reserves the right to change these Terms at any time. We recommend that you periodically check this Site for changes.
	
				<br />
				<br />
				<br />
	            <h4>Usage License</h4>
	            <div class="desc">
		            Subject to the terms and conditions set forth herein, Inqwise grants you a limited, non transferable license to access the Site and use the Services in accordance with these Terms and the instructions and guidelines posted on the Site, solely for your own use. You agree that your failure to adhere to any of the following conditions shall constitute a breach of these Terms on your part:<br />
		            <br />
		            <b>1.1</b> In order to use the Services, you must submit certain identifying information, which must be accurate and updated. It being clarified that the information will be kept and maintained by Inqwise according to the provisions of theses Terms of Service and the Privacy Policy of Inqwise as posted on the Site.<br />
		            <b>1.2</b> You are responsible for any activity that occurs under your screen name or caller ID.<br />
		            <b>1.3</b> You are responsible for keeping your password secure.<br />
		            <b>1.4</b> You must not abuse, harass, threaten, impersonate or intimidate other users of the Site or the Inqwise Services.<br />
		            <b>1.5</b> You may not use the Site or the Services for any illegal or unauthorized purpose. International users agree to comply with all local laws regarding online conduct and acceptable content.<br />
		            <b>1.6</b> You are solely responsible for your conduct and any data, text, information, screen names, graphics, photos, profiles, audio and video clips, links that you create, submit, post, and display on or through the Site or Services, including any advertising or other content made available to you or submitted by you and any website or other content published by or associated with you (the "<b>Content</b>"). You understand that all Content which you may have access to as part of, or through your use of the Services are the sole responsibility of the person from which such content originated. You hereby acknowledge and agree that if you use any of the Services to contribute or make available Content, Inqwise is hereby granted a non-exclusive, worldwide, royalty-free, transferable right to fully exploit such Content (including all related intellectual property rights) and to allow others to do so in connection with the Services and the Site.<br />
		            <b>1.7</b> Content presented to you at the Site or as part of the Services, including but not limited to advertisements within the Services may be protected by intellectual property rights which are owned by the sponsors or Advertisers who provide that Content to Inqwise (or by other persons or companies on their behalf). You may not modify, rent, lease, loan, sell, distribute or create derivative works based on this Content (either in whole or in part) unless you have been specifically told that you may do so by Inqwise or by the owners of that Content, in a separate written agreement.<br />
		            <b>1.8</b> You must not modify, adapt or hack the Site or modify another website, application or service so as to falsely imply that it is associated with the Site or the Inqwise Services.<br />
		            <b>1.9</b> You must not create or submit unwanted email or args of any form to any other users or members of the Site or the Inqwise Services.<br />
		            <b>1.10</b> You must not distribute any part of or parts of the Site, the Services or the Content, in any medium or through any media formats or through any media channels without Inqwise's prior written authorization;<br />
		            <b>1.11</b> You must not transmit any worms or viruses or any code of a destructive nature.<br />
		            <b>1.12</b> You must not, in the use of the Site or the Services, including by the uploading or downloading of Content violate any laws in your jurisdiction (including but not limited to copyright laws).<br />
		            <b>1.13</b> You must not infringe any patent, patent application, trademark, trade secret, copyright, right of publicity or any other right of any other person or entity.<br />
		            <b>1.14</b> You must not collect or harvest any personally identifiable information, including, without limitation, account names or caller IDs from the Site.<br />
		            <b>1.15</b> You must not post or upload any Content that is unlawful, threatening, abusive, harassing, defamatory, libelous, deceptive, fraudulent, invasive of another's privacy, tortuous, obscene, offensive or profane.<br />
		            <b>1.16</b> You must not circumvent, disable or otherwise interfere with any security related features of the Site and the Services.<br />
		            <b>1.17</b> You may use the Site and the Services solely for your personal, non-commercial use. Violation of any of these agreements will result in the termination of your account and Inqwise preserves the right to deny and block your access to the Site.<br />
		            All rights to use the Site and Services are provided on a non exclusive basis. Inqwise reserves the rights to terminate your license to use the Site at any time and for any reason.
				</div>
	            <h4>User Responsibility</h4>
	            <div class="desc">
		            <b>2.1</b> By using the Services, you represent and warrant that (a) you are 18 years of age or older; and (b) your use of the Services does not violate any applicable law or regulation. Your account may be terminated without warning, if we believe that you are under 18 years of age, if we believe that you are under 18 years of age and you represent yourself as 18 or older, or if we believe you are over 18 and represent yourself as under 18.<br />
		            <b>2.2</b> When you sign up to Inqwise, you will also be asked to choose a password. You are entirely responsible for maintaining the confidentiality of your password. You agree not to use the account, username, or password of another member at any time or to disclose your password to any third party. You agree to notify Inqwise immediately if you suspect any unauthorized use of your account or access to your password. You are solely responsible for any and all use of your account.<br />
		            <b>2.3</b> You are solely responsible for your use of the Site and Services. Because Inqwise merely serves as a repository of information, user-posted content does not represent the advice, views, opinions or beliefs of Inqwise, and Inqwise makes no claim of accuracy of any user-posted material.<br />
		            <b>2.4</b> Inqwise archives links to third-party websites. The linked websites' content, business practices and privacy policies are not under our control, and we are not responsible for the content of any linked website or any link contained in a linked website. The inclusion of a link on the Site or Services does not imply any endorsement by or any affiliation with Inqwise. In accessing the Site and Services or following links to third-party websites you may be exposed to content that you consider offensive or inappropriate. You agree that your only recourse is to stop using the Site and Services.<br />
		            <b>2.5</b> You understand that by accessing the Site or using the Services you may be exposed to Content that you may find offensive, indecent or objectionable and that, in this respect, you use the Services at your own risk.
				</div>
	            <h4>The Services</h4>
	            <div class="desc">
		            <b>3.1</b> Inqwise's Site offers a platform through which media buyers, advertising agencies and any other person who may be interested (each, an "<b>Advertiser</b>") may advertise such Advertiser's services/products upon "CAPTCHAS" that are placed by websites operators who are interested in such service ("<b>Publisher</b>"). The Services provided by the Inqwise enable to facilitate, promote, monitor and manage the performance of advertising campaigns upon CAPTCHAS ("<b>Advertised CAPTCHA</b>"), as more fully described on the Site and as selected by the Advertiser or the Publisher (as the case may be) through the application process provided on the Site.<br />
		            <b>3.2</b> Inqwise may change, suspend or discontinue the Services at any time, including the availability of any feature, advertisement, publisher or content, without notice or liability. Inqwise reserves the right (but shall have no obligation) to pre-screen, review, flag, filter, modify, refuse to display or remove any or all Content from the Services. Inqwise reserves the right, at its discretion, to refuse to allow access to the Services to any applicant at any time and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to the Content or if Inqwise is concerned that an Advertiser or a Publisher may have breached the terms of this Agreement).
				</div>
	            <h4>Confidential Information and Non-Disclosure</h4>
	            <div class="desc">
		            <b>4.1</b> The term "<b>Confidential Information</b>" shall include all information provided by Inqwise to you, or your affiliates, employees, officers, directors, agents or representatives, including without limitation, the Web Site and any and all of Inqwise's design specifications, drawings, written manuals, software programs, business plans, financial information, technical and marketing information and evaluations, service plans and customer information designated orally or in writing as confidential or otherwise which by its nature should be considered confidential. For purposes herein, Inqwise shall be deemed the "<b>Disclosing Party</b>" and you shall be deemed the "Receiving Party." Confidential Information shall not include information which can be demonstrated: (a) to have been rightfully in the possession of the Receiving Party from a source other than the Disclosing Party prior to the time of disclosure of said information to the Receiving Party ("<b>Time of Disclosure</b>"); (b) to have been in the public domain prior to the Time of Disclosure; (c) to have become part of the public domain after the Time of Disclosure by a publication or by any other means, except an unauthorized act or omission or breach of this Agreement on the part of the Receiving Party, or its employees; (d) to have been supplied to the Receiving Party after the Time of Disclosure without restriction by a third party who is under no obligation to the Disclosing Party to maintain such information in confidence; or (e) to be required to be disclosed by law or court order, provided that the Receiving Party shall provide the Disclosing Party with prompt notice sufficient for the Disclosing Party to have a reasonable opportunity to prevent such disclosure and shall use best efforts to limit the information to be disclosed.<br />
		            <b>4.2</b> If the Receiving Party or any of its affiliates, employees, officers, directors, agents or representatives shall attempt to improperly use or knowingly disclose any of the Confidential Information, the Disclosing Party shall have the right, in addition to such other remedies which may be available to it, to injunctive relief enjoining such acts or attempts; it being acknowledged that legal remedies are inadequate.
				</div>
	            <h4>Limitation of Liability</h4>
	            <div class="desc">
		            THE SERVICES, CONTENT AND THE SITE ARE PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. Inqwise DOES NOT WARRANT THE RESULTS OF USE OF THE SERVICES, INCLUDING, WITHOUT LIMITATION, THE RESULTS OF ANY ADVERTISING CAMPAIGN, AND EACH OF ADVERTISER AND PUBLISHER ASSUMES ALL RISK AND RESPONSIBILITY WITH RESPECT THERETO.<br />
		            IN NO EVENT SHALL Inqwise BE LIABLE TO USER, ADVERTISER, PUBLISHER AND ANY OF THEIR EMPLOYEES, AGENTS OR ANY OTHER THIRD PARTIES FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE OR EXEMPLARY DAMAGES OR LOSSES, INCLUDING WITHOUT LIMITATION LOSS OF USE, LOSS OF OR DAMAGE TO RECORDS OR DATA, COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNOLOGY, REVENUE AND/OR PROFITS, SUSTAINED OR INCURRED REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT OR OTHERWISE, INCLUDING WITHOUT LIMITATION NEGLIGENCE, STRICT LIABILITY, INDEMNITY OR OTHERWISE, AND WHETHER OR NOT SUCH DAMAGES WERE FORESEEN OR UNFORESEEN AND REGARDLESS OF WHETHER Inqwise HAD RECEIVED NOTICE OR HAD BEEN ADVISED, OR KNEW OR SHOULD HAVE KNOWN, OF THE POSSIBILITY OF SUCH DAMAGES OR LOSSES. WITHOUT LIMITATION OF THE FOREGOING, Inqwise'S MAXIMUM LIABILITY FOR ANY AND ALL LOSSES OR DAMAGES (INCLUDING WITHOUT LIMITATION ANY LEGAL FEES OR EXPENSES) INCURRED BY A USER, ADVERTISER OR PUBLISHER IN CONNECTION WITH THIS AGREEMENT SHALL NOT EXCEED US$ 10,000. IN NO EVENT SHALL Inqwise BE LIABLE FOR ANY CLAIM THAT AROSE MORE THAN ONE (1) YEAR PRIOR TO THE INSTITUTION OF A SUIT THEREON.
				</div>
	            <h4>Intellectual Property (Trademarks & Copyrights)</h4>
	            <div class="desc">
		            <b>6.1</b> Inqwise owns and shall own all right, title, and interest in and to the Site, the Services, the Confidential Information, PII collected at the Site, original content included on the Site (such as text, graphics, logos, software and the compilation of all content on the Site), Inqwise's trademarks, trade names, design, and any other data submitted by end users in response to an advertisement, including all source code, object code, operating instructions, and interfaces developed for or relating to the Services and/or the Site, together with all modifications, enhancements, revisions, changes, copies, partial copies, translations, compilations, and derivative works thereto, including all copyrights and other intellectual property rights relating thereto (the "<b>Intellectual Property</b>"). Publisher and Advertiser will have no rights with respect to the Intellectual Property other than those expressly granted hereunder. Publisher, Advertiser and/or any other user shall have no right to develop (or to permit any third party to develop) any software tool or other application that interfaces with the Services or the Site. To the extent Publisher, Advertiser or user develops (or permits any third party to develop) any such tool or other application in violation of the preceding sentence, all right, title, and interest in and to such tool (including any intellectual property rights with respect thereto) shall be deemed to be included in the Intellectual Property. To the extent any rights to any Intellectual Property would otherwise vest in Publisher or Advertiser, or any of their Affiliates, or any of their respective contractors or personnel: (i) Publisher/Advertiser hereby assigns (and shall cause its applicable affiliate or other contractors or personnel to assign) to Inqwise all right, title, and interest in and to such Intellectual Property and (ii) upon Inqwise's request, Publisher/Advertiser shall execute (and shall cause each applicable affiliate or other contractors or personnel to execute) such documents and provide such other assistance as may reasonably be requested by Inqwise to further evidence and perfect such assignment.<br />
		            "PII" (Personally Identifiable Information), shall mean any piece of information which can be used to uniquely identify, contact, or locate a single person, or can be used with other sources to uniquely identify a single person.<br />
		            <b>6.2</b> Inqwise, in its sole discretion, shall have the right to copy, sell, distribute, transfer, lease, assign, market, use, license, and re-market the non-PII collected at the Site (the "<b>Data</b>") and any PII voluntarily provided by end users at the Site without further obligation to any end user.
				</div>
	            <h4>Privacy</h4>
	            <div class="desc">
	            	The use of the Services herein is also governed by our <a href="PrivacyPolicy.aspx">Privacy Policy</a>, which is incorporated into these Terms of Service by this reference.
				</div>
	            <h4>Miscellaneous</h4>
	            <div class="desc">
		            <b>8.1</b> The Terms constitute the whole legal agreement between you and Inqwise and govern your use of the Site and the Services and completely replace any prior agreements between you and Inqwise in relation to the Site or the Services.<br />
		            <b>8.2</b> Inqwise and you are independent entities, and nothing in the Terms, or via use of the Site or the Services, will create any partnership, joint venture, agency, franchise, sales representative, or employment relationship between Inqwise and you.<br />
		            <b>8.3</b> You agree that Inqwise may provide you with notices and\or argss and\or other materials, including but not limited to those regarding changes of the Terms, and marketing or commercial argss by email, regular mail, postings on the Site or during video call sessions, and text argss to mobile phone. If you wish to stop receiving notices, please e-mail us to <a href="mailto:support@Inqwise.com">support@Inqwise.com</a>.<br />
		            <b>8.4</b> You agree that if Inqwise does not exercise or enforce any legal right or remedy which is contained in the Terms (or which Inqwise has the benefit of under any applicable law), this will not be taken to be a formal waiver of Inqwise's rights and that those rights or remedies will still be available to Inqwise.<br />
		            <b>8.5</b> No other person or company shall be a third party beneficiary of the Terms.<br />
		            <b>8.6</b> The Terms, and your relationship with Inqwise under the Terms, shall be governed exclusively by Israeli law. Any claim or dispute between you and Inqwise that arises in whole or in part from the Services or from the Terms shall be decided exclusively by the authorized courts of the State of Israel in the District of Tel Aviv-Jaffa. Notwithstanding this, you agree that Inqwise shall still be allowed to apply for injunctive remedies (or other equivalent types of urgent legal remedy) in any jurisdiction.<br />
		            <b>8.7</b> If any provision of the Terms is adjudged to be illegal or unenforceable, the continuation in full force of the remainder of the Terms will not be prejudiced, and the illegal or unenforceable provision of the Terms shall be severed accordingly.
	        	</div>
			</div>
        	</div>
        </div>
    </div>
</asp:content>